fixtures:
  repositories:
    provision: 'https://github.com/puppetlabs/provision.git'
  forge_modules:
    concat:
      repo: "puppetlabs/concat"
      ref: "8.0.1"
    mysql:
      repo: "puppetlabs/mysql"
      ref: "14.0.0"
    stdlib:
      repo: "puppetlabs/stdlib"
      ref: "9.0.0"
    archive:
      repo: "puppet/archive"
      ref: "6.1.2"
  symlinks:
    wordpress: "#{source_dir}"
